# Generated by Django 3.0.3 on 2020-03-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_comment', models.CharField(max_length=255)),
                ('expense_done_on', models.DateField()),
                ('expense_amount', models.IntegerField()),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseApp.Employee')),
                ('vendor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseApp.Vendor')),
            ],
        ),
    ]
